version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.1.6
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.6.3
            bundle install
            bundle exec rake
